### ISSUE TITLE
zict.Zip set bytearray

### ISSUE THREAD

**Issue by alimanfoo** [mrocklin/zict#1]
Would it be possible for Zip to allow setting of bytearray values in addition to bytes? Currently an exception is raised for anything other than bytes. In Zarr there is a possible optimisation within the blosc compressor which requires using bytearray instead of bytes (to prevent an additional memory copy) but this cannot be used with zict currently.

**Comment by mrocklin** [comment]
We're currently using the `zipfile` stdlib module, which doesn't efficiently support `bytearray`s.  We can always convert/copy internally though rather than require user code to handle it.

**Comment by mrocklin** [comment]
Fixed

**Comment by alimanfoo** [comment]
Thank you.

On Mon, May 9, 2016 at 4:46 PM, Matthew Rocklin <notifications@github.com>
wrote:

> Fixed
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mrocklin/zict/issues/1#issuecomment-217903519>
>



-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
Following on from discussion [here](https://github.com/alimanfoo/zarr/pull/22#issuecomment-217988661), could I suggest removing the ``isinstance`` check completely and just passing whatever value is given to ``__setitem__`` through to ``ZipFile.writestr``? This would give ``zict.Zip`` the same flexibility as the underlying ``zipfile`` module in terms of the range of value types accepted.

**Comment by mrocklin** [comment]
Done.

**Comment by alimanfoo** [comment]
Cool, thanks.
